export interface NationalTeamPlayer {
  name: string;
  position: string;
  dateOfBirth: string;
  nationality: string;
  club: string;
}

export interface NationalTeamData {
  crest: string;
  players: NationalTeamPlayer[];
}

export type NationalTeamsMap = Record<string, NationalTeamData>;

export const NATIONAL_TEAMS: NationalTeamsMap = {
  Argentina: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/1/13/Flag_of_Argentina.svg',
    players: [
      {
        name: 'Emiliano Martínez',
        position: 'GK',
        dateOfBirth: '1992-09-02',
        nationality: 'Argentina',
        club: 'Aston Villa',
      },
      {
        name: 'Gerónimo Rulli',
        position: 'GK',
        dateOfBirth: '1992-05-20',
        nationality: 'Argentina',
        club: 'Ajax',
      },
      {
        name: 'Walter Benítez',
        position: 'GK',
        dateOfBirth: '1993-03-19',
        nationality: 'Argentina',
        club: 'PSV',
      },
      {
        name: 'Nahuel Molina',
        position: 'RB',
        dateOfBirth: '1998-04-06',
        nationality: 'Argentina',
        club: 'Atlético Madrid',
      },
      {
        name: 'Gonzalo Montiel',
        position: 'RB',
        dateOfBirth: '1997-01-01',
        nationality: 'Argentina',
        club: 'Sevilla',
      },
      {
        name: 'Cristian Romero',
        position: 'CB',
        dateOfBirth: '1998-06-27',
        nationality: 'Argentina',
        club: 'Tottenham',
      },
      {
        name: 'Nicolás Otamendi',
        position: 'CB',
        dateOfBirth: '1988-02-12',
        nationality: 'Argentina',
        club: 'Benfica',
      },
      {
        name: 'Lisandro Martínez',
        position: 'CB',
        dateOfBirth: '1998-01-18',
        nationality: 'Argentina',
        club: 'Manchester United',
      },
      {
        name: 'Nicolás Tagliafico',
        position: 'LB',
        dateOfBirth: '1992-08-31',
        nationality: 'Argentina',
        club: 'Lyon',
      },
      {
        name: 'Marcos Acuña',
        position: 'LB',
        dateOfBirth: '1991-10-28',
        nationality: 'Argentina',
        club: 'Sevilla',
      },
      {
        name: 'Rodrigo De Paul',
        position: 'CM',
        dateOfBirth: '1994-05-24',
        nationality: 'Argentina',
        club: 'Atlético Madrid',
      },
      {
        name: 'Leandro Paredes',
        position: 'CDM',
        dateOfBirth: '1994-06-29',
        nationality: 'Argentina',
        club: 'Roma',
      },
      {
        name: 'Enzo Fernández',
        position: 'CM',
        dateOfBirth: '2001-01-17',
        nationality: 'Argentina',
        club: 'Chelsea',
      },
      {
        name: 'Alexis Mac Allister',
        position: 'CM',
        dateOfBirth: '1998-12-24',
        nationality: 'Argentina',
        club: 'Liverpool',
      },
      {
        name: 'Exequiel Palacios',
        position: 'CM',
        dateOfBirth: '1998-10-05',
        nationality: 'Argentina',
        club: 'Bayer Leverkusen',
      },
      {
        name: 'Giovani Lo Celso',
        position: 'CAM',
        dateOfBirth: '1996-04-09',
        nationality: 'Argentina',
        club: 'Tottenham',
      },
      {
        name: 'Lionel Messi',
        position: 'RW',
        dateOfBirth: '1987-06-24',
        nationality: 'Argentina',
        club: 'Inter Miami',
      },
      {
        name: 'Ángel Di María',
        position: 'LW',
        dateOfBirth: '1988-02-14',
        nationality: 'Argentina',
        club: 'Benfica',
      },
      {
        name: 'Julián Álvarez',
        position: 'ST',
        dateOfBirth: '2000-01-31',
        nationality: 'Argentina',
        club: 'Manchester City',
      },
      {
        name: 'Lautaro Martínez',
        position: 'ST',
        dateOfBirth: '1997-08-22',
        nationality: 'Argentina',
        club: 'Inter Milan',
      },
      {
        name: 'Nicolás González',
        position: 'LW',
        dateOfBirth: '1998-04-06',
        nationality: 'Argentina',
        club: 'Fiorentina',
      },
      {
        name: 'Alejandro Garnacho',
        position: 'LW',
        dateOfBirth: '2004-07-01',
        nationality: 'Argentina',
        club: 'Manchester United',
      },
      {
        name: 'Paulo Dybala',
        position: 'CAM',
        dateOfBirth: '1993-11-15',
        nationality: 'Argentina',
        club: 'Roma',
      },
      {
        name: 'Thiago Almada',
        position: 'CAM',
        dateOfBirth: '2001-04-11',
        nationality: 'Argentina',
        club: 'Botafogo',
      },
      {
        name: 'Valentín Barco',
        position: 'LB',
        dateOfBirth: '2004-07-23',
        nationality: 'Argentina',
        club: 'Brighton',
      },
      {
        name: 'Nahuel Gallardo',
        position: 'LB',
        dateOfBirth: '1998-09-30',
        nationality: 'Argentina',
        club: 'River Plate',
      },
    ],
  },
  Brazil: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Brazil.svg',
    players: [
      {
        name: 'Alisson',
        position: 'GK',
        dateOfBirth: '1992-10-02',
        nationality: 'Brazil',
        club: 'Liverpool',
      },
      {
        name: 'Ederson',
        position: 'GK',
        dateOfBirth: '1993-08-17',
        nationality: 'Brazil',
        club: 'Manchester City',
      },
      {
        name: 'Bento',
        position: 'GK',
        dateOfBirth: '1999-11-10',
        nationality: 'Brazil',
        club: 'Al-Nassr',
      },
      {
        name: 'Danilo',
        position: 'RB',
        dateOfBirth: '1991-07-15',
        nationality: 'Brazil',
        club: 'Juventus',
      },
      {
        name: 'Éder Militão',
        position: 'CB',
        dateOfBirth: '1998-01-18',
        nationality: 'Brazil',
        club: 'Real Madrid',
      },
      {
        name: 'Marquinhos',
        position: 'CB',
        dateOfBirth: '1994-05-14',
        nationality: 'Brazil',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Gabriel Magalhães',
        position: 'CB',
        dateOfBirth: '1997-12-19',
        nationality: 'Brazil',
        club: 'Arsenal',
      },
      {
        name: 'Alex Sandro',
        position: 'LB',
        dateOfBirth: '1991-01-26',
        nationality: 'Brazil',
        club: 'Flamengo',
      },
      {
        name: 'Guilherme Arana',
        position: 'LB',
        dateOfBirth: '1997-04-14',
        nationality: 'Brazil',
        club: 'Atlético Mineiro',
      },
      {
        name: 'Casemiro',
        position: 'CDM',
        dateOfBirth: '1992-02-23',
        nationality: 'Brazil',
        club: 'Manchester United',
      },
      {
        name: 'Bruno Guimarães',
        position: 'CM',
        dateOfBirth: '1997-11-16',
        nationality: 'Brazil',
        club: 'Newcastle',
      },
      {
        name: 'André',
        position: 'CDM',
        dateOfBirth: '2001-04-06',
        nationality: 'Brazil',
        club: 'Wolverhampton',
      },
      {
        name: 'Lucas Paquetá',
        position: 'CM',
        dateOfBirth: '1997-08-27',
        nationality: 'Brazil',
        club: 'West Ham',
      },
      {
        name: 'Joelinton',
        position: 'CM',
        dateOfBirth: '1996-08-14',
        nationality: 'Brazil',
        club: 'Newcastle',
      },
      {
        name: 'Neymar',
        position: 'LW',
        dateOfBirth: '1992-02-05',
        nationality: 'Brazil',
        club: 'Santos',
      },
      {
        name: 'Vinícius Júnior',
        position: 'LW',
        dateOfBirth: '2000-07-12',
        nationality: 'Brazil',
        club: 'Real Madrid',
      },
      {
        name: 'Raphinha',
        position: 'RW',
        dateOfBirth: '1996-12-14',
        nationality: 'Brazil',
        club: 'Barcelona',
      },
      {
        name: 'Rodrygo',
        position: 'RW',
        dateOfBirth: '2001-01-09',
        nationality: 'Brazil',
        club: 'Real Madrid',
      },
      {
        name: 'Gabriel Jesus',
        position: 'ST',
        dateOfBirth: '1997-04-03',
        nationality: 'Brazil',
        club: 'Arsenal',
      },
      {
        name: 'Richarlison',
        position: 'ST',
        dateOfBirth: '1997-05-10',
        nationality: 'Brazil',
        club: 'Tottenham',
      },
      {
        name: 'Endrick',
        position: 'ST',
        dateOfBirth: '2006-07-21',
        nationality: 'Brazil',
        club: 'Real Madrid',
      },
      {
        name: 'Savinho',
        position: 'RW',
        dateOfBirth: '2004-04-10',
        nationality: 'Brazil',
        club: 'Manchester City',
      },
      {
        name: 'Igor Julio',
        position: 'CB',
        dateOfBirth: '1998-02-07',
        nationality: 'Brazil',
        club: 'Brighton',
      },
      {
        name: 'Wendell',
        position: 'LB',
        dateOfBirth: '1997-07-20',
        nationality: 'Brazil',
        club: 'Porto',
      },
      {
        name: 'Pepê',
        position: 'RW',
        dateOfBirth: '1997-02-24',
        nationality: 'Brazil',
        club: 'Porto',
      },
      {
        name: 'Estêvão',
        position: 'RW',
        dateOfBirth: '2005-04-24',
        nationality: 'Brazil',
        club: 'Palmeiras',
      },
    ],
  },
  France: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg',
    players: [
      {
        name: 'Mike Maignan',
        position: 'GK',
        dateOfBirth: '1995-07-03',
        nationality: 'France',
        club: 'AC Milan',
      },
      {
        name: 'Alphonse Areola',
        position: 'GK',
        dateOfBirth: '1993-02-27',
        nationality: 'France',
        club: 'West Ham',
      },
      {
        name: 'Brice Samba',
        position: 'GK',
        dateOfBirth: '1994-04-25',
        nationality: 'France',
        club: 'Lens',
      },
      {
        name: 'Jules Koundé',
        position: 'RB',
        dateOfBirth: '1998-11-12',
        nationality: 'France',
        club: 'Barcelona',
      },
      {
        name: 'Benjamin Pavard',
        position: 'RB',
        dateOfBirth: '1996-03-28',
        nationality: 'France',
        club: 'Inter Milan',
      },
      {
        name: 'Dayot Upamecano',
        position: 'CB',
        dateOfBirth: '1998-10-27',
        nationality: 'France',
        club: 'Bayern Munich',
      },
      {
        name: 'Ibrahima Konaté',
        position: 'CB',
        dateOfBirth: '1999-05-25',
        nationality: 'France',
        club: 'Liverpool',
      },
      {
        name: 'William Saliba',
        position: 'CB',
        dateOfBirth: '2001-03-24',
        nationality: 'France',
        club: 'Arsenal',
      },
      {
        name: 'Theo Hernández',
        position: 'LB',
        dateOfBirth: '1997-10-06',
        nationality: 'France',
        club: 'AC Milan',
      },
      {
        name: 'Ferland Mendy',
        position: 'LB',
        dateOfBirth: '1995-06-08',
        nationality: 'France',
        club: 'Real Madrid',
      },
      {
        name: 'Aurélien Tchouaméni',
        position: 'CDM',
        dateOfBirth: '2000-01-27',
        nationality: 'France',
        club: 'Real Madrid',
      },
      {
        name: "N'Golo Kanté",
        position: 'CDM',
        dateOfBirth: '1991-03-29',
        nationality: 'France',
        club: 'Al-Ittihad',
      },
      {
        name: 'Adrien Rabiot',
        position: 'CM',
        dateOfBirth: '1995-04-03',
        nationality: 'France',
        club: 'Marseille',
      },
      {
        name: 'Eduardo Camavinga',
        position: 'CM',
        dateOfBirth: '2002-11-10',
        nationality: 'France',
        club: 'Real Madrid',
      },
      {
        name: 'Antoine Griezmann',
        position: 'CAM',
        dateOfBirth: '1991-03-21',
        nationality: 'France',
        club: 'Atlético Madrid',
      },
      {
        name: 'Kylian Mbappé',
        position: 'ST',
        dateOfBirth: '1998-12-20',
        nationality: 'France',
        club: 'Real Madrid',
      },
      {
        name: 'Olivier Giroud',
        position: 'ST',
        dateOfBirth: '1986-09-30',
        nationality: 'France',
        club: 'LAFC',
      },
      {
        name: 'Ousmane Dembélé',
        position: 'RW',
        dateOfBirth: '1997-05-15',
        nationality: 'France',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Kingsley Coman',
        position: 'LW',
        dateOfBirth: '1996-06-13',
        nationality: 'France',
        club: 'Bayern Munich',
      },
      {
        name: 'Marcus Thuram',
        position: 'ST',
        dateOfBirth: '1997-08-06',
        nationality: 'France',
        club: 'Inter Milan',
      },
      {
        name: 'Randal Kolo Muani',
        position: 'ST',
        dateOfBirth: '1998-12-05',
        nationality: 'France',
        club: 'Juventus',
      },
      {
        name: 'Bradley Barcola',
        position: 'LW',
        dateOfBirth: '2002-09-02',
        nationality: 'France',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Warren Zaïre-Emery',
        position: 'CM',
        dateOfBirth: '2006-03-08',
        nationality: 'France',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Matteo Guendouzi',
        position: 'CM',
        dateOfBirth: '1999-04-14',
        nationality: 'France',
        club: 'Lazio',
      },
      {
        name: 'Jean-Clair Todibo',
        position: 'CB',
        dateOfBirth: '1999-12-30',
        nationality: 'France',
        club: 'West Ham',
      },
      {
        name: 'Lucas Digne',
        position: 'LB',
        dateOfBirth: '1993-07-20',
        nationality: 'France',
        club: 'Aston Villa',
      },
    ],
  },
  Germany: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg',
    players: [
      {
        name: 'Manuel Neuer',
        position: 'GK',
        dateOfBirth: '1986-03-27',
        nationality: 'Germany',
        club: 'Bayern Munich',
      },
      {
        name: 'Marc-André ter Stegen',
        position: 'GK',
        dateOfBirth: '1992-04-30',
        nationality: 'Germany',
        club: 'Barcelona',
      },
      {
        name: 'Oliver Baumann',
        position: 'GK',
        dateOfBirth: '1990-06-02',
        nationality: 'Germany',
        club: 'Hoffenheim',
      },
      {
        name: 'Joshua Kimmich',
        position: 'RB',
        dateOfBirth: '1995-02-08',
        nationality: 'Germany',
        club: 'Bayern Munich',
      },
      {
        name: 'Antonio Rüdiger',
        position: 'CB',
        dateOfBirth: '1993-03-03',
        nationality: 'Germany',
        club: 'Real Madrid',
      },
      {
        name: 'Nico Schlotterbeck',
        position: 'CB',
        dateOfBirth: '1999-12-01',
        nationality: 'Germany',
        club: 'Borussia Dortmund',
      },
      {
        name: 'Jonathan Tah',
        position: 'CB',
        dateOfBirth: '1996-09-11',
        nationality: 'Germany',
        club: 'Bayer Leverkusen',
      },
      {
        name: 'David Raum',
        position: 'LB',
        dateOfBirth: '1998-04-22',
        nationality: 'Germany',
        club: 'RB Leipzig',
      },
      {
        name: 'Waldemar Anton',
        position: 'CB',
        dateOfBirth: '1996-07-20',
        nationality: 'Germany',
        club: 'Borussia Dortmund',
      },
      {
        name: 'Toni Kroos',
        position: 'CM',
        dateOfBirth: '1990-01-04',
        nationality: 'Germany',
        club: 'Real Madrid',
      },
      {
        name: 'İlkay Gündoğan',
        position: 'CM',
        dateOfBirth: '1990-10-24',
        nationality: 'Germany',
        club: 'Manchester City',
      },
      {
        name: 'Leroy Sané',
        position: 'RW',
        dateOfBirth: '1996-01-11',
        nationality: 'Germany',
        club: 'Bayern Munich',
      },
      {
        name: 'Jamal Musiala',
        position: 'CAM',
        dateOfBirth: '2003-02-26',
        nationality: 'Germany',
        club: 'Bayern Munich',
      },
      {
        name: 'Florian Wirtz',
        position: 'CAM',
        dateOfBirth: '2003-05-03',
        nationality: 'Germany',
        club: 'Bayer Leverkusen',
      },
      {
        name: 'Kai Havertz',
        position: 'ST',
        dateOfBirth: '1999-06-11',
        nationality: 'Germany',
        club: 'Arsenal',
      },
      {
        name: 'Niclas Füllkrug',
        position: 'ST',
        dateOfBirth: '1993-02-09',
        nationality: 'Germany',
        club: 'West Ham',
      },
      {
        name: 'Thomas Müller',
        position: 'CAM',
        dateOfBirth: '1989-09-13',
        nationality: 'Germany',
        club: 'Bayern Munich',
      },
      {
        name: 'Serge Gnabry',
        position: 'RW',
        dateOfBirth: '1995-07-14',
        nationality: 'Germany',
        club: 'Bayern Munich',
      },
      {
        name: 'Pascal Groß',
        position: 'CM',
        dateOfBirth: '1991-05-15',
        nationality: 'Germany',
        club: 'Borussia Dortmund',
      },
      {
        name: 'Robert Andrich',
        position: 'CDM',
        dateOfBirth: '1994-09-22',
        nationality: 'Germany',
        club: 'Bayer Leverkusen',
      },
      {
        name: 'Chris Führich',
        position: 'LW',
        dateOfBirth: '1998-01-27',
        nationality: 'Germany',
        club: 'Stuttgart',
      },
      {
        name: 'Deniz Undav',
        position: 'ST',
        dateOfBirth: '1996-07-19',
        nationality: 'Germany',
        club: 'Stuttgart',
      },
      {
        name: 'Maximilian Mittelstädt',
        position: 'LB',
        dateOfBirth: '1997-03-18',
        nationality: 'Germany',
        club: 'Stuttgart',
      },
      {
        name: 'Benjamin Henrichs',
        position: 'RB',
        dateOfBirth: '1997-02-23',
        nationality: 'Germany',
        club: 'RB Leipzig',
      },
      {
        name: 'Robin Gosens',
        position: 'LB',
        dateOfBirth: '1994-07-05',
        nationality: 'Germany',
        club: 'Fiorentina',
      },
      {
        name: 'Aleksandar Pavlović',
        position: 'CM',
        dateOfBirth: '2004-05-03',
        nationality: 'Germany',
        club: 'Bayern Munich',
      },
    ],
  },
  Spain: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Spain.svg',
    players: [
      {
        name: 'Unai Simón',
        position: 'GK',
        dateOfBirth: '1997-06-11',
        nationality: 'Spain',
        club: 'Athletic Bilbao',
      },
      {
        name: 'David Raya',
        position: 'GK',
        dateOfBirth: '1995-09-15',
        nationality: 'Spain',
        club: 'Arsenal',
      },
      {
        name: 'Álex Remiro',
        position: 'GK',
        dateOfBirth: '1995-03-24',
        nationality: 'Spain',
        club: 'Real Sociedad',
      },
      {
        name: 'Dani Carvajal',
        position: 'RB',
        dateOfBirth: '1992-01-11',
        nationality: 'Spain',
        club: 'Real Madrid',
      },
      {
        name: 'Aymeric Laporte',
        position: 'CB',
        dateOfBirth: '1994-05-27',
        nationality: 'Spain',
        club: 'Al-Nassr',
      },
      {
        name: 'Robin Le Normand',
        position: 'CB',
        dateOfBirth: '1996-11-11',
        nationality: 'Spain',
        club: 'Atlético Madrid',
      },
      {
        name: 'Dani Vivian',
        position: 'CB',
        dateOfBirth: '1999-07-15',
        nationality: 'Spain',
        club: 'Athletic Bilbao',
      },
      {
        name: 'Álex Grimaldo',
        position: 'LB',
        dateOfBirth: '1995-09-20',
        nationality: 'Spain',
        club: 'Bayer Leverkusen',
      },
      {
        name: 'Jordi Alba',
        position: 'LB',
        dateOfBirth: '1989-03-21',
        nationality: 'Spain',
        club: 'Inter Miami',
      },
      {
        name: 'Rodri',
        position: 'CDM',
        dateOfBirth: '1996-06-22',
        nationality: 'Spain',
        club: 'Manchester City',
      },
      {
        name: 'Martín Zubimendi',
        position: 'CDM',
        dateOfBirth: '1999-02-02',
        nationality: 'Spain',
        club: 'Real Sociedad',
      },
      {
        name: 'Pedri',
        position: 'CM',
        dateOfBirth: '2002-11-25',
        nationality: 'Spain',
        club: 'Barcelona',
      },
      {
        name: 'Fabián Ruiz',
        position: 'CM',
        dateOfBirth: '1996-04-03',
        nationality: 'Spain',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Mikel Merino',
        position: 'CM',
        dateOfBirth: '1996-06-22',
        nationality: 'Spain',
        club: 'Arsenal',
      },
      {
        name: 'Lamine Yamal',
        position: 'RW',
        dateOfBirth: '2007-07-13',
        nationality: 'Spain',
        club: 'Barcelona',
      },
      {
        name: 'Nico Williams',
        position: 'LW',
        dateOfBirth: '2002-07-12',
        nationality: 'Spain',
        club: 'Athletic Bilbao',
      },
      {
        name: 'Dani Olmo',
        position: 'CAM',
        dateOfBirth: '1998-05-07',
        nationality: 'Spain',
        club: 'Barcelona',
      },
      {
        name: 'Fermín López',
        position: 'CM',
        dateOfBirth: '2003-05-11',
        nationality: 'Spain',
        club: 'Barcelona',
      },
      {
        name: 'Álvaro Morata',
        position: 'ST',
        dateOfBirth: '1992-10-23',
        nationality: 'Spain',
        club: 'AC Milan',
      },
      {
        name: 'Joselu',
        position: 'ST',
        dateOfBirth: '1990-03-27',
        nationality: 'Spain',
        club: 'Al-Gharafa',
      },
      {
        name: 'Mikel Oyarzabal',
        position: 'LW',
        dateOfBirth: '1997-04-21',
        nationality: 'Spain',
        club: 'Real Sociedad',
      },
      {
        name: 'Pau Torres',
        position: 'CB',
        dateOfBirth: '1997-01-16',
        nationality: 'Spain',
        club: 'Aston Villa',
      },
      {
        name: 'Marc Cucurella',
        position: 'LB',
        dateOfBirth: '1998-07-22',
        nationality: 'Spain',
        club: 'Chelsea',
      },
      {
        name: 'Alejandro Balde',
        position: 'LB',
        dateOfBirth: '2003-06-18',
        nationality: 'Spain',
        club: 'Barcelona',
      },
      {
        name: 'Bryan Zaragoza',
        position: 'LW',
        dateOfBirth: '2001-09-09',
        nationality: 'Spain',
        club: 'Osasuna',
      },
    ],
  },
  England: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/b/be/Flag_of_England.svg',
    players: [
      {
        name: 'Jordan Pickford',
        position: 'GK',
        dateOfBirth: '1994-03-07',
        nationality: 'England',
        club: 'Everton',
      },
      {
        name: 'Aaron Ramsdale',
        position: 'GK',
        dateOfBirth: '1998-05-14',
        nationality: 'England',
        club: 'Southampton',
      },
      {
        name: 'Dean Henderson',
        position: 'GK',
        dateOfBirth: '1997-03-12',
        nationality: 'England',
        club: 'Crystal Palace',
      },
      {
        name: 'Kyle Walker',
        position: 'RB',
        dateOfBirth: '1990-05-28',
        nationality: 'England',
        club: 'Manchester City',
      },
      {
        name: 'Kieran Trippier',
        position: 'RB',
        dateOfBirth: '1990-09-19',
        nationality: 'England',
        club: 'Newcastle',
      },
      {
        name: 'John Stones',
        position: 'CB',
        dateOfBirth: '1994-05-28',
        nationality: 'England',
        club: 'Manchester City',
      },
      {
        name: 'Harry Maguire',
        position: 'CB',
        dateOfBirth: '1993-03-05',
        nationality: 'England',
        club: 'Manchester United',
      },
      {
        name: 'Marc Guéhi',
        position: 'CB',
        dateOfBirth: '2000-07-13',
        nationality: 'England',
        club: 'Crystal Palace',
      },
      {
        name: 'Luke Shaw',
        position: 'LB',
        dateOfBirth: '1995-07-12',
        nationality: 'England',
        club: 'Manchester United',
      },
      {
        name: 'Ben Chilwell',
        position: 'LB',
        dateOfBirth: '1996-12-21',
        nationality: 'England',
        club: 'Chelsea',
      },
      {
        name: 'Declan Rice',
        position: 'CDM',
        dateOfBirth: '1999-01-14',
        nationality: 'England',
        club: 'Arsenal',
      },
      {
        name: 'Jude Bellingham',
        position: 'CM',
        dateOfBirth: '2003-06-29',
        nationality: 'England',
        club: 'Real Madrid',
      },
      {
        name: 'Phil Foden',
        position: 'CAM',
        dateOfBirth: '2000-05-28',
        nationality: 'England',
        club: 'Manchester City',
      },
      {
        name: 'Conor Gallagher',
        position: 'CM',
        dateOfBirth: '2000-02-06',
        nationality: 'England',
        club: 'Atlético Madrid',
      },
      {
        name: 'Bukayo Saka',
        position: 'RW',
        dateOfBirth: '2001-09-05',
        nationality: 'England',
        club: 'Arsenal',
      },
      {
        name: 'Harry Kane',
        position: 'ST',
        dateOfBirth: '1993-07-28',
        nationality: 'England',
        club: 'Bayern Munich',
      },
      {
        name: 'Jack Grealish',
        position: 'LW',
        dateOfBirth: '1995-09-10',
        nationality: 'England',
        club: 'Manchester City',
      },
      {
        name: 'Marcus Rashford',
        position: 'LW',
        dateOfBirth: '1997-10-31',
        nationality: 'England',
        club: 'Manchester United',
      },
      {
        name: 'Ollie Watkins',
        position: 'ST',
        dateOfBirth: '1995-12-30',
        nationality: 'England',
        club: 'Aston Villa',
      },
      {
        name: 'Cole Palmer',
        position: 'CAM',
        dateOfBirth: '2002-05-06',
        nationality: 'England',
        club: 'Chelsea',
      },
      {
        name: 'Ezri Konsa',
        position: 'CB',
        dateOfBirth: '1997-10-23',
        nationality: 'England',
        club: 'Aston Villa',
      },
      {
        name: 'Joe Gomez',
        position: 'CB',
        dateOfBirth: '1997-05-23',
        nationality: 'England',
        club: 'Liverpool',
      },
      {
        name: 'Eberechi Eze',
        position: 'CAM',
        dateOfBirth: '1998-06-29',
        nationality: 'England',
        club: 'Crystal Palace',
      },
      {
        name: 'Ivan Toney',
        position: 'ST',
        dateOfBirth: '1996-03-16',
        nationality: 'England',
        club: 'Al-Ahli',
      },
      {
        name: 'Mason Mount',
        position: 'CM',
        dateOfBirth: '1999-01-10',
        nationality: 'England',
        club: 'Manchester United',
      },
    ],
  },
  Portugal: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg',
    players: [
      {
        name: 'Diogo Costa',
        position: 'GK',
        dateOfBirth: '1999-09-19',
        nationality: 'Portugal',
        club: 'Porto',
      },
      {
        name: 'Rui Patrício',
        position: 'GK',
        dateOfBirth: '1988-02-15',
        nationality: 'Portugal',
        club: 'Roma',
      },
      {
        name: 'José Sá',
        position: 'GK',
        dateOfBirth: '1993-01-17',
        nationality: 'Portugal',
        club: 'Wolverhampton',
      },
      {
        name: 'João Cancelo',
        position: 'RB',
        dateOfBirth: '1994-05-27',
        nationality: 'Portugal',
        club: 'Barcelona',
      },
      {
        name: 'Rúben Dias',
        position: 'CB',
        dateOfBirth: '1997-05-14',
        nationality: 'Portugal',
        club: 'Manchester City',
      },
      {
        name: 'António Silva',
        position: 'CB',
        dateOfBirth: '2003-10-30',
        nationality: 'Portugal',
        club: 'Benfica',
      },
      {
        name: 'Nuno Mendes',
        position: 'LB',
        dateOfBirth: '2002-06-19',
        nationality: 'Portugal',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Raphaël Guerreiro',
        position: 'LB',
        dateOfBirth: '1993-12-22',
        nationality: 'Portugal',
        club: 'Bayern Munich',
      },
      {
        name: 'Vitinha',
        position: 'CM',
        dateOfBirth: '2000-02-13',
        nationality: 'Portugal',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Bruno Fernandes',
        position: 'CAM',
        dateOfBirth: '1994-09-08',
        nationality: 'Portugal',
        club: 'Manchester United',
      },
      {
        name: 'Bernardo Silva',
        position: 'CM',
        dateOfBirth: '1994-08-10',
        nationality: 'Portugal',
        club: 'Manchester City',
      },
      {
        name: 'João Palhinha',
        position: 'CDM',
        dateOfBirth: '1995-07-09',
        nationality: 'Portugal',
        club: 'Bayern Munich',
      },
      {
        name: 'Rúben Neves',
        position: 'CM',
        dateOfBirth: '1997-03-13',
        nationality: 'Portugal',
        club: 'Al-Hilal',
      },
      {
        name: 'Cristiano Ronaldo',
        position: 'ST',
        dateOfBirth: '1985-02-05',
        nationality: 'Portugal',
        club: 'Al-Nassr',
      },
      {
        name: 'Diogo Jota',
        position: 'ST',
        dateOfBirth: '1996-12-04',
        nationality: 'Portugal',
        club: 'Liverpool',
      },
      {
        name: 'Rafael Leão',
        position: 'LW',
        dateOfBirth: '1999-06-10',
        nationality: 'Portugal',
        club: 'AC Milan',
      },
      {
        name: 'Gonçalo Ramos',
        position: 'ST',
        dateOfBirth: '2001-06-20',
        nationality: 'Portugal',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Francisco Conceição',
        position: 'RW',
        dateOfBirth: '2002-12-14',
        nationality: 'Portugal',
        club: 'Juventus',
      },
      {
        name: 'Pedro Neto',
        position: 'RW',
        dateOfBirth: '2000-03-09',
        nationality: 'Portugal',
        club: 'Chelsea',
      },
      {
        name: 'Nélson Semedo',
        position: 'RB',
        dateOfBirth: '1993-11-16',
        nationality: 'Portugal',
        club: 'Wolverhampton',
      },
      {
        name: 'Matheus Nunes',
        position: 'CM',
        dateOfBirth: '1998-08-27',
        nationality: 'Portugal',
        club: 'Manchester City',
      },
      {
        name: 'Danilo Pereira',
        position: 'CDM',
        dateOfBirth: '1991-09-09',
        nationality: 'Portugal',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Diogo Dalot',
        position: 'RB',
        dateOfBirth: '1999-03-18',
        nationality: 'Portugal',
        club: 'Manchester United',
      },
      {
        name: 'Otávio',
        position: 'CM',
        dateOfBirth: '1995-02-09',
        nationality: 'Portugal',
        club: 'Al-Nassr',
      },
      {
        name: 'Pepe',
        position: 'CB',
        dateOfBirth: '1983-02-26',
        nationality: 'Portugal',
        club: 'Porto',
      },
      {
        name: 'Bruma',
        position: 'RW',
        dateOfBirth: '1994-10-24',
        nationality: 'Portugal',
        club: 'Braga',
      },
    ],
  },
  Netherlands: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg',
    players: [
      {
        name: 'Justin Bijlow',
        position: 'GK',
        dateOfBirth: '1998-01-22',
        nationality: 'Netherlands',
        club: 'Feyenoord',
      },
      {
        name: 'Bart Verbruggen',
        position: 'GK',
        dateOfBirth: '2002-08-18',
        nationality: 'Netherlands',
        club: 'Brighton',
      },
      {
        name: 'Mark Flekken',
        position: 'GK',
        dateOfBirth: '1993-06-13',
        nationality: 'Netherlands',
        club: 'Brentford',
      },
      {
        name: 'Denzel Dumfries',
        position: 'RB',
        dateOfBirth: '1996-04-18',
        nationality: 'Netherlands',
        club: 'Inter Milan',
      },
      {
        name: 'Virgil van Dijk',
        position: 'CB',
        dateOfBirth: '1991-07-08',
        nationality: 'Netherlands',
        club: 'Liverpool',
      },
      {
        name: 'Stefan de Vrij',
        position: 'CB',
        dateOfBirth: '1992-02-05',
        nationality: 'Netherlands',
        club: 'Inter Milan',
      },
      {
        name: 'Nathan Aké',
        position: 'CB',
        dateOfBirth: '1995-02-18',
        nationality: 'Netherlands',
        club: 'Manchester City',
      },
      {
        name: 'Micky van de Ven',
        position: 'CB',
        dateOfBirth: '2001-04-19',
        nationality: 'Netherlands',
        club: 'Tottenham',
      },
      {
        name: 'Daley Blind',
        position: 'LB',
        dateOfBirth: '1990-03-09',
        nationality: 'Netherlands',
        club: 'Girona',
      },
      {
        name: 'Frenkie de Jong',
        position: 'CM',
        dateOfBirth: '1997-05-12',
        nationality: 'Netherlands',
        club: 'Barcelona',
      },
      {
        name: 'Mats Wieffer',
        position: 'CDM',
        dateOfBirth: '1999-11-16',
        nationality: 'Netherlands',
        club: 'Brighton',
      },
      {
        name: 'Teun Koopmeiners',
        position: 'CM',
        dateOfBirth: '1998-02-28',
        nationality: 'Netherlands',
        club: 'Juventus',
      },
      {
        name: 'Tijjani Reijnders',
        position: 'CM',
        dateOfBirth: '1998-07-29',
        nationality: 'Netherlands',
        club: 'AC Milan',
      },
      {
        name: 'Jeremie Frimpong',
        position: 'RB',
        dateOfBirth: '2000-12-10',
        nationality: 'Netherlands',
        club: 'Bayer Leverkusen',
      },
      {
        name: 'Cody Gakpo',
        position: 'LW',
        dateOfBirth: '1999-05-07',
        nationality: 'Netherlands',
        club: 'Liverpool',
      },
      {
        name: 'Xavi Simons',
        position: 'CAM',
        dateOfBirth: '2003-04-21',
        nationality: 'Netherlands',
        club: 'RB Leipzig',
      },
      {
        name: 'Memphis Depay',
        position: 'ST',
        dateOfBirth: '1994-02-13',
        nationality: 'Netherlands',
        club: 'Corinthians',
      },
      {
        name: 'Wout Weghorst',
        position: 'ST',
        dateOfBirth: '1992-08-07',
        nationality: 'Netherlands',
        club: 'Ajax',
      },
      {
        name: 'Donyell Malen',
        position: 'ST',
        dateOfBirth: '1999-01-19',
        nationality: 'Netherlands',
        club: 'Borussia Dortmund',
      },
      {
        name: 'Steven Bergwijn',
        position: 'LW',
        dateOfBirth: '1997-10-08',
        nationality: 'Netherlands',
        club: 'Ajax',
      },
      {
        name: 'Donny van de Beek',
        position: 'CM',
        dateOfBirth: '1997-04-18',
        nationality: 'Netherlands',
        club: 'Girona',
      },
      {
        name: 'Jurriën Timber',
        position: 'RB',
        dateOfBirth: '2001-06-17',
        nationality: 'Netherlands',
        club: 'Arsenal',
      },
      {
        name: 'Lutsharel Geertruida',
        position: 'CB',
        dateOfBirth: '2000-07-18',
        nationality: 'Netherlands',
        club: 'RB Leipzig',
      },
      {
        name: 'Ian Maatsen',
        position: 'LB',
        dateOfBirth: '2002-03-10',
        nationality: 'Netherlands',
        club: 'Aston Villa',
      },
      {
        name: 'Brian Brobbey',
        position: 'ST',
        dateOfBirth: '2002-02-01',
        nationality: 'Netherlands',
        club: 'Ajax',
      },
    ],
  },
  Italy: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Italy.svg',
    players: [
      {
        name: 'Gianluigi Donnarumma',
        position: 'GK',
        dateOfBirth: '1999-02-25',
        nationality: 'Italy',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Alex Meret',
        position: 'GK',
        dateOfBirth: '1997-03-22',
        nationality: 'Italy',
        club: 'Napoli',
      },
      {
        name: 'Guglielmo Vicario',
        position: 'GK',
        dateOfBirth: '1996-10-06',
        nationality: 'Italy',
        club: 'Tottenham',
      },
      {
        name: 'Giovanni Di Lorenzo',
        position: 'RB',
        dateOfBirth: '1993-08-04',
        nationality: 'Italy',
        club: 'Napoli',
      },
      {
        name: 'Alessandro Bastoni',
        position: 'CB',
        dateOfBirth: '1999-04-13',
        nationality: 'Italy',
        club: 'Inter Milan',
      },
      {
        name: 'Francesco Acerbi',
        position: 'CB',
        dateOfBirth: '1988-02-10',
        nationality: 'Italy',
        club: 'Inter Milan',
      },
      {
        name: 'Gianluca Mancini',
        position: 'CB',
        dateOfBirth: '1996-04-17',
        nationality: 'Italy',
        club: 'Roma',
      },
      {
        name: 'Federico Dimarco',
        position: 'LB',
        dateOfBirth: '1997-11-10',
        nationality: 'Italy',
        club: 'Inter Milan',
      },
      {
        name: 'Giorgio Scalvini',
        position: 'CB',
        dateOfBirth: '2003-12-11',
        nationality: 'Italy',
        club: 'Atalanta',
      },
      {
        name: 'Jorginho',
        position: 'CDM',
        dateOfBirth: '1991-12-20',
        nationality: 'Italy',
        club: 'Arsenal',
      },
      {
        name: 'Nicolò Barella',
        position: 'CM',
        dateOfBirth: '1997-02-07',
        nationality: 'Italy',
        club: 'Inter Milan',
      },
      {
        name: 'Sandro Tonali',
        position: 'CM',
        dateOfBirth: '2000-05-08',
        nationality: 'Italy',
        club: 'Newcastle',
      },
      {
        name: 'Davide Frattesi',
        position: 'CM',
        dateOfBirth: '1999-09-22',
        nationality: 'Italy',
        club: 'Inter Milan',
      },
      {
        name: 'Lorenzo Pellegrini',
        position: 'CAM',
        dateOfBirth: '1996-06-19',
        nationality: 'Italy',
        club: 'Roma',
      },
      {
        name: 'Federico Chiesa',
        position: 'RW',
        dateOfBirth: '1997-10-25',
        nationality: 'Italy',
        club: 'Liverpool',
      },
      {
        name: 'Ciro Immobile',
        position: 'ST',
        dateOfBirth: '1990-02-20',
        nationality: 'Italy',
        club: 'Beşiktaş',
      },
      {
        name: 'Giacomo Raspadori',
        position: 'ST',
        dateOfBirth: '2000-02-18',
        nationality: 'Italy',
        club: 'Napoli',
      },
      {
        name: 'Mateo Retegui',
        position: 'ST',
        dateOfBirth: '1999-04-29',
        nationality: 'Italy',
        club: 'Atalanta',
      },
      {
        name: 'Stephan El Shaarawy',
        position: 'LW',
        dateOfBirth: '1992-10-27',
        nationality: 'Italy',
        club: 'Roma',
      },
      {
        name: 'Andrea Cambiaso',
        position: 'LB',
        dateOfBirth: '2000-02-20',
        nationality: 'Italy',
        club: 'Juventus',
      },
      {
        name: 'Raoul Bellanova',
        position: 'RB',
        dateOfBirth: '2000-05-17',
        nationality: 'Italy',
        club: 'Atalanta',
      },
      {
        name: 'Riccardo Orsolini',
        position: 'RW',
        dateOfBirth: '1997-01-24',
        nationality: 'Italy',
        club: 'Bologna',
      },
      {
        name: 'Manuel Locatelli',
        position: 'CM',
        dateOfBirth: '1998-01-08',
        nationality: 'Italy',
        club: 'Juventus',
      },
      {
        name: 'Bryan Cristante',
        position: 'CM',
        dateOfBirth: '1995-03-30',
        nationality: 'Italy',
        club: 'Roma',
      },
      {
        name: 'Wilfried Gnonto',
        position: 'LW',
        dateOfBirth: '2003-11-05',
        nationality: 'Italy',
        club: 'Leeds',
      },
    ],
  },
  Belgium: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg',
    players: [
      {
        name: 'Thibaut Courtois',
        position: 'GK',
        dateOfBirth: '1992-05-11',
        nationality: 'Belgium',
        club: 'Real Madrid',
      },
      {
        name: 'Koen Casteels',
        position: 'GK',
        dateOfBirth: '1992-06-25',
        nationality: 'Belgium',
        club: 'Al-Qadsiah',
      },
      {
        name: 'Matz Sels',
        position: 'GK',
        dateOfBirth: '1992-02-26',
        nationality: 'Belgium',
        club: 'Nottingham Forest',
      },
      {
        name: 'Thomas Meunier',
        position: 'RB',
        dateOfBirth: '1991-09-12',
        nationality: 'Belgium',
        club: 'Lille',
      },
      {
        name: 'Jan Vertonghen',
        position: 'CB',
        dateOfBirth: '1987-04-24',
        nationality: 'Belgium',
        club: 'Anderlecht',
      },
      {
        name: 'Wout Faes',
        position: 'CB',
        dateOfBirth: '1998-04-08',
        nationality: 'Belgium',
        club: 'Leicester City',
      },
      {
        name: 'Arthur Theate',
        position: 'CB',
        dateOfBirth: '2000-05-25',
        nationality: 'Belgium',
        club: 'Rennes',
      },
      {
        name: 'Timothy Castagne',
        position: 'LB',
        dateOfBirth: '1995-12-05',
        nationality: 'Belgium',
        club: 'Fulham',
      },
      {
        name: 'Kevin De Bruyne',
        position: 'CAM',
        dateOfBirth: '1991-06-28',
        nationality: 'Belgium',
        club: 'Manchester City',
      },
      {
        name: 'Youri Tielemans',
        position: 'CM',
        dateOfBirth: '1997-05-07',
        nationality: 'Belgium',
        club: 'Aston Villa',
      },
      {
        name: 'Amadou Onana',
        position: 'CDM',
        dateOfBirth: '2001-08-16',
        nationality: 'Belgium',
        club: 'Aston Villa',
      },
      {
        name: 'Leandro Trossard',
        position: 'LW',
        dateOfBirth: '1994-12-04',
        nationality: 'Belgium',
        club: 'Arsenal',
      },
      {
        name: 'Romelu Lukaku',
        position: 'ST',
        dateOfBirth: '1993-05-13',
        nationality: 'Belgium',
        club: 'Napoli',
      },
      {
        name: 'Dries Mertens',
        position: 'LW',
        dateOfBirth: '1987-05-06',
        nationality: 'Belgium',
        club: 'Galatasaray',
      },
      {
        name: 'Yannick Carrasco',
        position: 'LW',
        dateOfBirth: '1993-09-04',
        nationality: 'Belgium',
        club: 'Al-Shabab',
      },
      {
        name: 'Charles De Ketelaere',
        position: 'CAM',
        dateOfBirth: '2001-03-10',
        nationality: 'Belgium',
        club: 'Atalanta',
      },
      {
        name: 'Loïs Openda',
        position: 'ST',
        dateOfBirth: '2000-02-16',
        nationality: 'Belgium',
        club: 'RB Leipzig',
      },
      {
        name: 'Jérémy Doku',
        position: 'RW',
        dateOfBirth: '2002-10-27',
        nationality: 'Belgium',
        club: 'Manchester City',
      },
      {
        name: 'Orel Mangala',
        position: 'CM',
        dateOfBirth: '1998-03-18',
        nationality: 'Belgium',
        club: 'Lyon',
      },
      {
        name: 'Alexis Saelemaekers',
        position: 'RW',
        dateOfBirth: '1999-06-27',
        nationality: 'Belgium',
        club: 'Roma',
      },
      {
        name: 'Zeno Debast',
        position: 'CB',
        dateOfBirth: '2003-10-24',
        nationality: 'Belgium',
        club: 'Sporting CP',
      },
      {
        name: 'Roméo Lavia',
        position: 'CDM',
        dateOfBirth: '2004-01-06',
        nationality: 'Belgium',
        club: 'Chelsea',
      },
      {
        name: 'Michy Batshuayi',
        position: 'ST',
        dateOfBirth: '1993-10-02',
        nationality: 'Belgium',
        club: 'Galatasaray',
      },
      {
        name: 'Dodi Lukebakio',
        position: 'RW',
        dateOfBirth: '1997-09-24',
        nationality: 'Belgium',
        club: 'Sevilla',
      },
    ],
  },
  Croatia: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg',
    players: [
      {
        name: 'Dominik Livaković',
        position: 'GK',
        dateOfBirth: '1995-01-09',
        nationality: 'Croatia',
        club: 'Fenerbahçe',
      },
      {
        name: 'Ivica Ivušić',
        position: 'GK',
        dateOfBirth: '1995-02-01',
        nationality: 'Croatia',
        club: 'Istra 1961',
      },
      {
        name: 'Nediljko Labrović',
        position: 'GK',
        dateOfBirth: '1999-10-10',
        nationality: 'Croatia',
        club: 'Rijeka',
      },
      {
        name: 'Joško Gvardiol',
        position: 'CB',
        dateOfBirth: '2002-02-23',
        nationality: 'Croatia',
        club: 'Manchester City',
      },
      {
        name: 'Dejan Lovren',
        position: 'CB',
        dateOfBirth: '1989-07-05',
        nationality: 'Croatia',
        club: 'PAOK',
      },
      {
        name: 'Duje Ćaleta-Car',
        position: 'CB',
        dateOfBirth: '1996-09-17',
        nationality: 'Croatia',
        club: 'Lyon',
      },
      {
        name: 'Borna Sosa',
        position: 'LB',
        dateOfBirth: '1998-01-21',
        nationality: 'Croatia',
        club: 'Sevilla',
      },
      {
        name: 'Josip Juranović',
        position: 'RB',
        dateOfBirth: '1995-08-16',
        nationality: 'Croatia',
        club: 'Union Berlin',
      },
      {
        name: 'Marcelo Brozović',
        position: 'CDM',
        dateOfBirth: '1992-11-16',
        nationality: 'Croatia',
        club: 'Al-Nassr',
      },
      {
        name: 'Luka Modrić',
        position: 'CM',
        dateOfBirth: '1985-09-09',
        nationality: 'Croatia',
        club: 'Real Madrid',
      },
      {
        name: 'Mateo Kovačić',
        position: 'CM',
        dateOfBirth: '1994-05-06',
        nationality: 'Croatia',
        club: 'Manchester City',
      },
      {
        name: 'Mario Pašalić',
        position: 'CM',
        dateOfBirth: '1995-02-09',
        nationality: 'Croatia',
        club: 'Atalanta',
      },
      {
        name: 'Lovro Majer',
        position: 'CAM',
        dateOfBirth: '1998-01-17',
        nationality: 'Croatia',
        club: 'Wolfsburg',
      },
      {
        name: 'Ivan Perišić',
        position: 'LW',
        dateOfBirth: '1989-02-02',
        nationality: 'Croatia',
        club: 'PSV',
      },
      {
        name: 'Andrej Kramarić',
        position: 'ST',
        dateOfBirth: '1991-06-19',
        nationality: 'Croatia',
        club: 'Hoffenheim',
      },
      {
        name: 'Bruno Petković',
        position: 'ST',
        dateOfBirth: '1994-09-16',
        nationality: 'Croatia',
        club: 'Dinamo Zagreb',
      },
      {
        name: 'Ante Budimir',
        position: 'ST',
        dateOfBirth: '1991-07-22',
        nationality: 'Croatia',
        club: 'Osasuna',
      },
      {
        name: 'Marko Livaja',
        position: 'ST',
        dateOfBirth: '1993-08-26',
        nationality: 'Croatia',
        club: 'Hajduk Split',
      },
      {
        name: 'Nikola Vlašić',
        position: 'CAM',
        dateOfBirth: '1997-10-04',
        nationality: 'Croatia',
        club: 'Torino',
      },
      {
        name: 'Kristijan Jakić',
        position: 'CDM',
        dateOfBirth: '1997-05-14',
        nationality: 'Croatia',
        club: 'Augsburg',
      },
      {
        name: 'Martin Baturina',
        position: 'CAM',
        dateOfBirth: '2003-02-16',
        nationality: 'Croatia',
        club: 'Dinamo Zagreb',
      },
      {
        name: 'Luka Sučić',
        position: 'CM',
        dateOfBirth: '2002-09-08',
        nationality: 'Croatia',
        club: 'Real Sociedad',
      },
      {
        name: 'Domagoj Vida',
        position: 'CB',
        dateOfBirth: '1989-04-29',
        nationality: 'Croatia',
        club: 'AEK Athens',
      },
    ],
  },
  Uruguay: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg',
    players: [
      {
        name: 'Sergio Rochet',
        position: 'GK',
        dateOfBirth: '1993-08-23',
        nationality: 'Uruguay',
        club: 'Inter Miami',
      },
      {
        name: 'Sebastián Sosa',
        position: 'GK',
        dateOfBirth: '1994-08-19',
        nationality: 'Uruguay',
        club: 'Racing Club',
      },
      {
        name: 'Santiago Mele',
        position: 'GK',
        dateOfBirth: '1997-09-22',
        nationality: 'Uruguay',
        club: 'Lanús',
      },
      {
        name: 'Nahitan Nández',
        position: 'RB',
        dateOfBirth: '1994-12-25',
        nationality: 'Uruguay',
        club: 'Al-Qadsiah',
      },
      {
        name: 'José Giménez',
        position: 'CB',
        dateOfBirth: '1995-01-20',
        nationality: 'Uruguay',
        club: 'Atlético Madrid',
      },
      {
        name: 'Sebastián Cáceres',
        position: 'CB',
        dateOfBirth: '1999-08-18',
        nationality: 'Uruguay',
        club: 'América',
      },
      {
        name: 'Ronald Araújo',
        position: 'CB',
        dateOfBirth: '1999-08-26',
        nationality: 'Uruguay',
        club: 'Barcelona',
      },
      {
        name: 'Mathías Olivera',
        position: 'LB',
        dateOfBirth: '1997-10-31',
        nationality: 'Uruguay',
        club: 'Napoli',
      },
      {
        name: 'Rodrigo Bentancur',
        position: 'CM',
        dateOfBirth: '1997-06-25',
        nationality: 'Uruguay',
        club: 'Tottenham',
      },
      {
        name: 'Federico Valverde',
        position: 'CM',
        dateOfBirth: '1998-07-22',
        nationality: 'Uruguay',
        club: 'Real Madrid',
      },
      {
        name: 'Manuel Ugarte',
        position: 'CDM',
        dateOfBirth: '2001-04-11',
        nationality: 'Uruguay',
        club: 'Manchester United',
      },
      {
        name: 'Giorgian De Arrascaeta',
        position: 'CAM',
        dateOfBirth: '1994-06-01',
        nationality: 'Uruguay',
        club: 'Flamengo',
      },
      {
        name: 'Nicolás De La Cruz',
        position: 'CM',
        dateOfBirth: '1997-06-01',
        nationality: 'Uruguay',
        club: 'River Plate',
      },
      {
        name: 'Facundo Pellistri',
        position: 'RW',
        dateOfBirth: '2001-12-20',
        nationality: 'Uruguay',
        club: 'Panathinaikos',
      },
      {
        name: 'Darwin Núñez',
        position: 'ST',
        dateOfBirth: '1999-06-24',
        nationality: 'Uruguay',
        club: 'Liverpool',
      },
      {
        name: 'Luis Suárez',
        position: 'ST',
        dateOfBirth: '1987-01-24',
        nationality: 'Uruguay',
        club: 'Inter Miami',
      },
      {
        name: 'Edinson Cavani',
        position: 'ST',
        dateOfBirth: '1987-02-14',
        nationality: 'Uruguay',
        club: 'Boca Juniors',
      },
      {
        name: 'Maximiliano Araújo',
        position: 'LW',
        dateOfBirth: '2000-02-15',
        nationality: 'Uruguay',
        club: 'Sporting CP',
      },
      {
        name: 'Agustín Canobbio',
        position: 'RW',
        dateOfBirth: '1998-10-01',
        nationality: 'Uruguay',
        club: 'Athletico Paranaense',
      },
      {
        name: 'Brian Rodríguez',
        position: 'LW',
        dateOfBirth: '2000-05-20',
        nationality: 'Uruguay',
        club: 'América',
      },
      {
        name: 'Sebastián Coates',
        position: 'CB',
        dateOfBirth: '1990-10-07',
        nationality: 'Uruguay',
        club: 'Sporting CP',
      },
      {
        name: 'Matías Viña',
        position: 'LB',
        dateOfBirth: '1997-11-09',
        nationality: 'Uruguay',
        club: 'Flamengo',
      },
      {
        name: 'Jonathan Rodríguez',
        position: 'ST',
        dateOfBirth: '1993-07-06',
        nationality: 'Uruguay',
        club: 'América',
      },
    ],
  },
  Colombia: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg',
    players: [
      {
        name: 'Camilo Vargas',
        position: 'GK',
        dateOfBirth: '1989-03-09',
        nationality: 'Colombia',
        club: 'Atlas',
      },
      {
        name: 'David Ospina',
        position: 'GK',
        dateOfBirth: '1988-08-31',
        nationality: 'Colombia',
        club: 'Al-Nassr',
      },
      {
        name: 'Álvaro Montero',
        position: 'GK',
        dateOfBirth: '1992-03-08',
        nationality: 'Colombia',
        club: 'Millonarios',
      },
      {
        name: 'Daniel Muñoz',
        position: 'RB',
        dateOfBirth: '1996-05-26',
        nationality: 'Colombia',
        club: 'Crystal Palace',
      },
      {
        name: 'Davinson Sánchez',
        position: 'CB',
        dateOfBirth: '1996-06-12',
        nationality: 'Colombia',
        club: 'Galatasaray',
      },
      {
        name: 'Yerry Mina',
        position: 'CB',
        dateOfBirth: '1994-09-23',
        nationality: 'Colombia',
        club: 'Fiorentina',
      },
      {
        name: 'Jhon Lucumí',
        position: 'CB',
        dateOfBirth: '1998-06-26',
        nationality: 'Colombia',
        club: 'Bologna',
      },
      {
        name: 'Johan Mojica',
        position: 'LB',
        dateOfBirth: '1992-08-21',
        nationality: 'Colombia',
        club: 'Osasuna',
      },
      {
        name: 'Jefferson Lerma',
        position: 'CDM',
        dateOfBirth: '1994-10-25',
        nationality: 'Colombia',
        club: 'Crystal Palace',
      },
      {
        name: 'Mateus Uribe',
        position: 'CM',
        dateOfBirth: '1991-03-21',
        nationality: 'Colombia',
        club: 'Al-Sadd',
      },
      {
        name: 'Richard Ríos',
        position: 'CM',
        dateOfBirth: '1999-06-02',
        nationality: 'Colombia',
        club: 'Palmeiras',
      },
      {
        name: 'James Rodríguez',
        position: 'CAM',
        dateOfBirth: '1991-07-12',
        nationality: 'Colombia',
        club: 'Rayo Vallecano',
      },
      {
        name: 'Juan Fernando Quintero',
        position: 'CAM',
        dateOfBirth: '1993-01-18',
        nationality: 'Colombia',
        club: 'Racing Club',
      },
      {
        name: 'Luis Díaz',
        position: 'LW',
        dateOfBirth: '1997-01-13',
        nationality: 'Colombia',
        club: 'Liverpool',
      },
      {
        name: 'Duván Zapata',
        position: 'ST',
        dateOfBirth: '1991-04-01',
        nationality: 'Colombia',
        club: 'Torino',
      },
      {
        name: 'Rafael Santos Borré',
        position: 'ST',
        dateOfBirth: '1995-09-08',
        nationality: 'Colombia',
        club: 'Werder Bremen',
      },
      {
        name: 'Jhon Córdoba',
        position: 'ST',
        dateOfBirth: '1993-05-25',
        nationality: 'Colombia',
        club: 'Krasnodar',
      },
      {
        name: 'Gustavo Cuéllar',
        position: 'CM',
        dateOfBirth: '1992-10-19',
        nationality: 'Colombia',
        club: 'Al-Shabab',
      },
      {
        name: 'Santiago Arias',
        position: 'RB',
        dateOfBirth: '1992-01-13',
        nationality: 'Colombia',
        club: 'Bahia',
      },
      {
        name: 'Kevin Mier',
        position: 'GK',
        dateOfBirth: '2000-05-18',
        nationality: 'Colombia',
        club: 'Atlas',
      },
      {
        name: 'Andrés Colorado',
        position: 'CM',
        dateOfBirth: '1998-12-24',
        nationality: 'Colombia',
        club: 'San Lorenzo',
      },
      {
        name: 'Miguel Borja',
        position: 'ST',
        dateOfBirth: '1991-01-26',
        nationality: 'Colombia',
        club: 'River Plate',
      },
    ],
  },
  Morocco: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg',
    players: [
      {
        name: 'Yassine Bounou',
        position: 'GK',
        dateOfBirth: '1991-04-05',
        nationality: 'Morocco',
        club: 'Al-Hilal',
      },
      {
        name: 'Munir El Kajoui',
        position: 'GK',
        dateOfBirth: '1989-05-10',
        nationality: 'Morocco',
        club: 'Al-Tawoun',
      },
      {
        name: 'Ahmed Reda Tagnaouti',
        position: 'GK',
        dateOfBirth: '1996-04-05',
        nationality: 'Morocco',
        club: 'Ismaily',
      },
      {
        name: 'Achraf Hakimi',
        position: 'RB',
        dateOfBirth: '1998-11-04',
        nationality: 'Morocco',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Romain Saïss',
        position: 'CB',
        dateOfBirth: '1990-03-26',
        nationality: 'Morocco',
        club: 'Al-Sadd',
      },
      {
        name: 'Nayef Aguerd',
        position: 'CB',
        dateOfBirth: '1996-03-30',
        nationality: 'Morocco',
        club: 'Real Sociedad',
      },
      {
        name: 'Achraf Dari',
        position: 'CB',
        dateOfBirth: '1997-05-06',
        nationality: 'Morocco',
        club: 'Al-Ettifaq',
      },
      {
        name: 'Noussair Mazraoui',
        position: 'LB',
        dateOfBirth: '1997-11-14',
        nationality: 'Morocco',
        club: 'Manchester United',
      },
      {
        name: 'Yahia Attiyat Allah',
        position: 'LB',
        dateOfBirth: '1995-03-02',
        nationality: 'Morocco',
        club: 'Wydad',
      },
      {
        name: 'Sofyan Amrabat',
        position: 'CDM',
        dateOfBirth: '1996-08-21',
        nationality: 'Morocco',
        club: 'Fenerbahçe',
      },
      {
        name: 'Azzedine Ounahi',
        position: 'CM',
        dateOfBirth: '2000-04-19',
        nationality: 'Morocco',
        club: 'Marseille',
      },
      {
        name: 'Bilal El Khannous',
        position: 'CAM',
        dateOfBirth: '2004-05-10',
        nationality: 'Morocco',
        club: 'Leicester City',
      },
      {
        name: 'Selim Amallah',
        position: 'CM',
        dateOfBirth: '1996-11-15',
        nationality: 'Morocco',
        club: 'Valladolid',
      },
      {
        name: 'Hakim Ziyech',
        position: 'RW',
        dateOfBirth: '1993-03-19',
        nationality: 'Morocco',
        club: 'Al-Duhail',
      },
      {
        name: 'Youssef En-Nesyri',
        position: 'ST',
        dateOfBirth: '1997-06-01',
        nationality: 'Morocco',
        club: 'Fenerbahçe',
      },
      {
        name: 'Soufiane Rahimi',
        position: 'LW',
        dateOfBirth: '1996-06-02',
        nationality: 'Morocco',
        club: 'Al-Ain',
      },
      {
        name: 'Abdelhamid Sabiri',
        position: 'CAM',
        dateOfBirth: '1996-11-28',
        nationality: 'Morocco',
        club: 'Fiorentina',
      },
      {
        name: 'Zakaria Aboukhlal',
        position: 'RW',
        dateOfBirth: '2000-02-18',
        nationality: 'Morocco',
        club: 'Toulouse',
      },
      {
        name: 'Ismaila Sarr',
        position: 'RW',
        dateOfBirth: '1998-02-25',
        nationality: 'Morocco',
        club: 'Crystal Palace',
      },
      {
        name: 'Walid Cheddira',
        position: 'ST',
        dateOfBirth: '1998-01-19',
        nationality: 'Morocco',
        club: 'Espanyol',
      },
      {
        name: 'Jawad El Yamiq',
        position: 'CB',
        dateOfBirth: '1992-02-29',
        nationality: 'Morocco',
        club: 'Al-Wehda',
      },
      {
        name: 'Adam Masina',
        position: 'LB',
        dateOfBirth: '1994-01-02',
        nationality: 'Morocco',
        club: 'Udinese',
      },
      {
        name: 'Amine Harit',
        position: 'CAM',
        dateOfBirth: '1997-06-18',
        nationality: 'Morocco',
        club: 'Marseille',
      },
    ],
  },
  Japan: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Japan.svg',
    players: [
      {
        name: 'Zion Suzuki',
        position: 'GK',
        dateOfBirth: '2002-08-21',
        nationality: 'Japan',
        club: 'Parma',
      },
      {
        name: 'Daniel Schmidt',
        position: 'GK',
        dateOfBirth: '1992-02-22',
        nationality: 'Japan',
        club: 'Gent',
      },
      {
        name: 'Shū Gonda',
        position: 'GK',
        dateOfBirth: '1989-03-03',
        nationality: 'Japan',
        club: 'Shonan Bellmare',
      },
      {
        name: 'Takehiro Tomiyasu',
        position: 'CB',
        dateOfBirth: '1998-11-05',
        nationality: 'Japan',
        club: 'Arsenal',
      },
      {
        name: 'Kō Itakura',
        position: 'CB',
        dateOfBirth: '1997-01-27',
        nationality: 'Japan',
        club: 'Borussia Mönchengladbach',
      },
      {
        name: 'Maya Yoshida',
        position: 'CB',
        dateOfBirth: '1988-08-24',
        nationality: 'Japan',
        club: 'LA Galaxy',
      },
      {
        name: 'Hiroki Sakai',
        position: 'RB',
        dateOfBirth: '1990-04-12',
        nationality: 'Japan',
        club: 'Auckland FC',
      },
      {
        name: 'Yuto Nagatomo',
        position: 'LB',
        dateOfBirth: '1986-09-12',
        nationality: 'Japan',
        club: 'FC Tokyo',
      },
      {
        name: 'Wataru Endō',
        position: 'CDM',
        dateOfBirth: '1993-02-09',
        nationality: 'Japan',
        club: 'Liverpool',
      },
      {
        name: 'Ao Tanaka',
        position: 'CM',
        dateOfBirth: '1998-09-10',
        nationality: 'Japan',
        club: 'Leeds',
      },
      {
        name: 'Hidemasa Morita',
        position: 'CM',
        dateOfBirth: '1995-05-10',
        nationality: 'Japan',
        club: 'Sporting CP',
      },
      {
        name: 'Ritsu Dōan',
        position: 'RW',
        dateOfBirth: '1998-06-16',
        nationality: 'Japan',
        club: 'Freiburg',
      },
      {
        name: 'Kaoru Mitoma',
        position: 'LW',
        dateOfBirth: '1997-05-20',
        nationality: 'Japan',
        club: 'Brighton',
      },
      {
        name: 'Takefusa Kubo',
        position: 'RW',
        dateOfBirth: '2001-06-04',
        nationality: 'Japan',
        club: 'Real Sociedad',
      },
      {
        name: 'Junya Itō',
        position: 'RW',
        dateOfBirth: '1993-03-09',
        nationality: 'Japan',
        club: 'Reims',
      },
      {
        name: 'Daizen Maeda',
        position: 'ST',
        dateOfBirth: '1997-10-20',
        nationality: 'Japan',
        club: 'Celtic',
      },
      {
        name: 'Ayase Ueda',
        position: 'ST',
        dateOfBirth: '1998-08-02',
        nationality: 'Japan',
        club: 'Feyenoord',
      },
      {
        name: 'Takumi Minamino',
        position: 'CAM',
        dateOfBirth: '1995-01-16',
        nationality: 'Japan',
        club: 'Monaco',
      },
      {
        name: 'Yuki Soma',
        position: 'LW',
        dateOfBirth: '1997-02-25',
        nationality: 'Japan',
        club: 'Nagoya Grampus',
      },
      {
        name: 'Takuma Asano',
        position: 'ST',
        dateOfBirth: '1994-11-10',
        nationality: 'Japan',
        club: 'VfL Bochum',
      },
      {
        name: 'Miki Yamane',
        position: 'RB',
        dateOfBirth: '1993-11-22',
        nationality: 'Japan',
        club: 'Kawasaki Frontale',
      },
      {
        name: 'Gaku Shibasaki',
        position: 'CM',
        dateOfBirth: '1992-05-28',
        nationality: 'Japan',
        club: 'Leganés',
      },
      {
        name: 'Kento Hashimoto',
        position: 'CM',
        dateOfBirth: '1993-05-21',
        nationality: 'Japan',
        club: 'Sint-Truiden',
      },
    ],
  },
  SouthKorea: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg',
    players: [
      {
        name: 'Kim Seung-gyu',
        position: 'GK',
        dateOfBirth: '1990-09-30',
        nationality: 'South Korea',
        club: 'Al-Shabab',
      },
      {
        name: 'Jo Hyeon-woo',
        position: 'GK',
        dateOfBirth: '1991-09-25',
        nationality: 'South Korea',
        club: 'Ulsan HD',
      },
      {
        name: 'Song Bum-kon',
        position: 'GK',
        dateOfBirth: '1990-03-15',
        nationality: 'South Korea',
        club: 'Jeonbuk Hyundai',
      },
      {
        name: 'Kim Min-jae',
        position: 'CB',
        dateOfBirth: '1996-11-15',
        nationality: 'South Korea',
        club: 'Bayern Munich',
      },
      {
        name: 'Kwon Kyung-won',
        position: 'CB',
        dateOfBirth: '1992-01-31',
        nationality: 'South Korea',
        club: 'Suwon FC',
      },
      {
        name: 'Kim Young-gwon',
        position: 'CB',
        dateOfBirth: '1990-02-27',
        nationality: 'South Korea',
        club: 'Al-Gharafa',
      },
      {
        name: 'Kim Jin-su',
        position: 'LB',
        dateOfBirth: '1992-06-13',
        nationality: 'South Korea',
        club: 'Jeonbuk Hyundai',
      },
      {
        name: 'Lee Yong',
        position: 'RB',
        dateOfBirth: '1986-12-24',
        nationality: 'South Korea',
        club: 'Jeonbuk Hyundai',
      },
      {
        name: 'Hwang In-beom',
        position: 'CM',
        dateOfBirth: '1996-09-20',
        nationality: 'South Korea',
        club: 'Feyenoord',
      },
      {
        name: 'Lee Kang-in',
        position: 'CAM',
        dateOfBirth: '2001-02-19',
        nationality: 'South Korea',
        club: 'Paris Saint-Germain',
      },
      {
        name: 'Son Heung-min',
        position: 'LW',
        dateOfBirth: '1992-07-08',
        nationality: 'South Korea',
        club: 'Tottenham',
      },
      {
        name: 'Hwang Hee-chan',
        position: 'ST',
        dateOfBirth: '1996-01-26',
        nationality: 'South Korea',
        club: 'Wolverhampton',
      },
      {
        name: 'Cho Gue-sung',
        position: 'ST',
        dateOfBirth: '1998-01-25',
        nationality: 'South Korea',
        club: 'Midtjylland',
      },
      {
        name: 'Paik Seung-ho',
        position: 'CM',
        dateOfBirth: '1997-03-24',
        nationality: 'South Korea',
        club: 'Birmingham City',
      },
      {
        name: 'Hong Chul',
        position: 'LB',
        dateOfBirth: '1990-06-17',
        nationality: 'South Korea',
        club: 'Daegu FC',
      },
      {
        name: 'Jung Woo-young',
        position: 'CM',
        dateOfBirth: '1989-12-14',
        nationality: 'South Korea',
        club: 'Al-Sailiya',
      },
      {
        name: 'Na Sang-ho',
        position: 'LW',
        dateOfBirth: '1996-08-02',
        nationality: 'South Korea',
        club: 'FC Seoul',
      },
      {
        name: 'Oh Se-hun',
        position: 'ST',
        dateOfBirth: '1996-01-07',
        nationality: 'South Korea',
        club: 'Machida Zelvia',
      },
      {
        name: 'Lee Jae-sung',
        position: 'CM',
        dateOfBirth: '1992-08-10',
        nationality: 'South Korea',
        club: 'Mainz 05',
      },
      {
        name: 'Kwon Chang-hoon',
        position: 'RW',
        dateOfBirth: '1994-06-30',
        nationality: 'South Korea',
        club: 'Gwangju FC',
      },
      {
        name: 'Park Yong-woo',
        position: 'CDM',
        dateOfBirth: '1993-09-12',
        nationality: 'South Korea',
        club: 'Al-Ain',
      },
      {
        name: 'Seol Young-woo',
        position: 'RB',
        dateOfBirth: '1998-12-05',
        nationality: 'South Korea',
        club: 'Zvezda',
      },
      {
        name: 'Jeong Woo-yeong',
        position: 'RW',
        dateOfBirth: '1999-09-15',
        nationality: 'South Korea',
        club: 'VfB Stuttgart',
      },
    ],
  },
  USA: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg',
    players: [
      {
        name: 'Matt Turner',
        position: 'GK',
        dateOfBirth: '1994-06-24',
        nationality: 'USA',
        club: 'Crystal Palace',
      },
      {
        name: 'Ethan Horvath',
        position: 'GK',
        dateOfBirth: '1995-06-09',
        nationality: 'USA',
        club: 'Cardiff City',
      },
      {
        name: 'Sean Johnson',
        position: 'GK',
        dateOfBirth: '1989-05-31',
        nationality: 'USA',
        club: 'Toronto FC',
      },
      {
        name: 'Sergiño Dest',
        position: 'RB',
        dateOfBirth: '2000-11-03',
        nationality: 'USA',
        club: 'PSV',
      },
      {
        name: 'Walker Zimmerman',
        position: 'CB',
        dateOfBirth: '1993-05-19',
        nationality: 'USA',
        club: 'Nashville SC',
      },
      {
        name: 'Tim Ream',
        position: 'CB',
        dateOfBirth: '1987-10-05',
        nationality: 'USA',
        club: 'Charlotte FC',
      },
      {
        name: 'Chris Richards',
        position: 'CB',
        dateOfBirth: '2000-03-28',
        nationality: 'USA',
        club: 'Crystal Palace',
      },
      {
        name: 'Antonee Robinson',
        position: 'LB',
        dateOfBirth: '1997-08-08',
        nationality: 'USA',
        club: 'Fulham',
      },
      {
        name: 'Tyler Adams',
        position: 'CDM',
        dateOfBirth: '1999-02-14',
        nationality: 'USA',
        club: 'Bournemouth',
      },
      {
        name: 'Weston McKennie',
        position: 'CM',
        dateOfBirth: '1998-08-28',
        nationality: 'USA',
        club: 'Juventus',
      },
      {
        name: 'Yunus Musah',
        position: 'CM',
        dateOfBirth: '2002-11-29',
        nationality: 'USA',
        club: 'AC Milan',
      },
      {
        name: 'Giovanni Reyna',
        position: 'CAM',
        dateOfBirth: '2002-11-13',
        nationality: 'USA',
        club: 'Borussia Dortmund',
      },
      {
        name: 'Christian Pulisic',
        position: 'LW',
        dateOfBirth: '1998-09-18',
        nationality: 'USA',
        club: 'AC Milan',
      },
      {
        name: 'Timothy Weah',
        position: 'RW',
        dateOfBirth: '2000-02-22',
        nationality: 'USA',
        club: 'Juventus',
      },
      {
        name: 'Brenden Aaronson',
        position: 'CAM',
        dateOfBirth: '2000-10-22',
        nationality: 'USA',
        club: 'Leeds',
      },
      {
        name: 'Folarin Balogun',
        position: 'ST',
        dateOfBirth: '2001-07-03',
        nationality: 'USA',
        club: 'Monaco',
      },
      {
        name: 'Ricardo Pepi',
        position: 'ST',
        dateOfBirth: '2003-01-09',
        nationality: 'USA',
        club: 'PSV',
      },
      {
        name: 'Haji Wright',
        position: 'ST',
        dateOfBirth: '1998-03-27',
        nationality: 'USA',
        club: 'Coventry City',
      },
      {
        name: 'Cameron Carter-Vickers',
        position: 'CB',
        dateOfBirth: '1997-12-31',
        nationality: 'USA',
        club: 'Celtic',
      },
      {
        name: 'Joe Scally',
        position: 'RB',
        dateOfBirth: '2003-04-21',
        nationality: 'USA',
        club: 'Borussia Mönchengladbach',
      },
      {
        name: 'Malik Tillman',
        position: 'CAM',
        dateOfBirth: '2002-05-28',
        nationality: 'USA',
        club: 'PSV',
      },
      {
        name: 'Josh Sargent',
        position: 'ST',
        dateOfBirth: '2000-02-20',
        nationality: 'USA',
        club: 'Norwich City',
      },
    ],
  },
  Switzerland: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg',
    players: [
      {
        name: 'Yann Sommer',
        position: 'GK',
        dateOfBirth: '1988-12-17',
        nationality: 'Switzerland',
        club: 'Inter Milan',
      },
      {
        name: 'Jonas Omlin',
        position: 'GK',
        dateOfBirth: '1994-01-10',
        nationality: 'Switzerland',
        club: 'Borussia Mönchengladbach',
      },
      {
        name: 'Gregor Kobel',
        position: 'GK',
        dateOfBirth: '1997-12-06',
        nationality: 'Switzerland',
        club: 'Borussia Dortmund',
      },
      {
        name: 'Silvan Widmer',
        position: 'RB',
        dateOfBirth: '1993-03-05',
        nationality: 'Switzerland',
        club: 'Mainz 05',
      },
      {
        name: 'Manuel Akanji',
        position: 'CB',
        dateOfBirth: '1995-07-19',
        nationality: 'Switzerland',
        club: 'Manchester City',
      },
      {
        name: 'Fabian Schär',
        position: 'CB',
        dateOfBirth: '1991-12-20',
        nationality: 'Switzerland',
        club: 'Newcastle',
      },
      {
        name: 'Ricardo Rodriguez',
        position: 'CB',
        dateOfBirth: '1992-08-25',
        nationality: 'Switzerland',
        club: 'Torino',
      },
      {
        name: 'Granit Xhaka',
        position: 'CM',
        dateOfBirth: '1992-09-27',
        nationality: 'Switzerland',
        club: 'Bayer Leverkusen',
      },
      {
        name: 'Remo Freuler',
        position: 'CM',
        dateOfBirth: '1992-04-15',
        nationality: 'Switzerland',
        club: 'Bologna',
      },
      {
        name: 'Denis Zakaria',
        position: 'CDM',
        dateOfBirth: '1996-11-20',
        nationality: 'Switzerland',
        club: 'Monaco',
      },
      {
        name: 'Xherdan Shaqiri',
        position: 'CAM',
        dateOfBirth: '1991-10-10',
        nationality: 'Switzerland',
        club: 'Chicago Fire',
      },
      {
        name: 'Steven Zuber',
        position: 'LW',
        dateOfBirth: '1991-08-17',
        nationality: 'Switzerland',
        club: 'AEK Athens',
      },
      {
        name: 'Ruben Vargas',
        position: 'LW',
        dateOfBirth: '1998-08-14',
        nationality: 'Switzerland',
        club: 'Sevilla',
      },
      {
        name: 'Breel Embolo',
        position: 'ST',
        dateOfBirth: '1997-02-14',
        nationality: 'Switzerland',
        club: 'Monaco',
      },
      {
        name: 'Haris Seferović',
        position: 'ST',
        dateOfBirth: '1992-02-22',
        nationality: 'Switzerland',
        club: 'Al-Wasl',
      },
      {
        name: 'Noah Okafor',
        position: 'LW',
        dateOfBirth: '2000-05-24',
        nationality: 'Switzerland',
        club: 'Napoli',
      },
      {
        name: 'Michel Aebischer',
        position: 'CM',
        dateOfBirth: '1997-01-06',
        nationality: 'Switzerland',
        club: 'Bologna',
      },
      {
        name: 'Edimilson Fernandes',
        position: 'CM',
        dateOfBirth: '1996-04-15',
        nationality: 'Switzerland',
        club: 'Mainz 05',
      },
      {
        name: 'Nico Elvedi',
        position: 'CB',
        dateOfBirth: '1996-09-30',
        nationality: 'Switzerland',
        club: 'Borussia Mönchengladbach',
      },
      {
        name: 'Jordan Lotomba',
        position: 'RB',
        dateOfBirth: '1998-09-29',
        nationality: 'Switzerland',
        club: 'Nice',
      },
      {
        name: 'Zeki Amdouni',
        position: 'ST',
        dateOfBirth: '2000-12-04',
        nationality: 'Switzerland',
        club: 'Benfica',
      },
      {
        name: 'Kwadwo Duah',
        position: 'ST',
        dateOfBirth: '1997-02-02',
        nationality: 'Switzerland',
        club: 'Ludogorets',
      },
      {
        name: 'Ardon Jashari',
        position: 'CM',
        dateOfBirth: '2002-07-02',
        nationality: 'Switzerland',
        club: 'Luzern',
      },
    ],
  },
  Denmark: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg',
    players: [
      {
        name: 'Kasper Schmeichel',
        position: 'GK',
        dateOfBirth: '1986-11-05',
        nationality: 'Denmark',
        club: 'Celtic',
      },
      {
        name: 'Frederik Rønnow',
        position: 'GK',
        dateOfBirth: '1992-08-04',
        nationality: 'Denmark',
        club: 'Union Berlin',
      },
      {
        name: 'Mads Hermansen',
        position: 'GK',
        dateOfBirth: '2000-07-11',
        nationality: 'Denmark',
        club: 'Leicester City',
      },
      {
        name: 'Andreas Christensen',
        position: 'CB',
        dateOfBirth: '1996-06-10',
        nationality: 'Denmark',
        club: 'Barcelona',
      },
      {
        name: 'Jannik Vestergaard',
        position: 'CB',
        dateOfBirth: '1992-08-03',
        nationality: 'Denmark',
        club: 'Leicester City',
      },
      {
        name: 'Simon Kjær',
        position: 'CB',
        dateOfBirth: '1989-03-26',
        nationality: 'Denmark',
        club: 'AC Milan',
      },
      {
        name: 'Joakim Mæhle',
        position: 'RB',
        dateOfBirth: '1997-05-20',
        nationality: 'Denmark',
        club: 'Wolfsburg',
      },
      {
        name: 'Victor Kristiansen',
        position: 'LB',
        dateOfBirth: '2002-12-16',
        nationality: 'Denmark',
        club: 'Leicester City',
      },
      {
        name: 'Christian Eriksen',
        position: 'CM',
        dateOfBirth: '1992-02-14',
        nationality: 'Denmark',
        club: 'Manchester United',
      },
      {
        name: 'Thomas Delaney',
        position: 'CDM',
        dateOfBirth: '1991-09-03',
        nationality: 'Denmark',
        club: 'Copenhagen',
      },
      {
        name: 'Pierre-Emile Højbjerg',
        position: 'CM',
        dateOfBirth: '1995-08-05',
        nationality: 'Denmark',
        club: 'Marseille',
      },
      {
        name: 'Mikkel Damsgaard',
        position: 'LW',
        dateOfBirth: '2000-07-03',
        nationality: 'Denmark',
        club: 'Brentford',
      },
      {
        name: 'Andreas Skov Olsen',
        position: 'RW',
        dateOfBirth: '1999-12-29',
        nationality: 'Denmark',
        club: 'Wolfsburg',
      },
      {
        name: 'Rasmus Højlund',
        position: 'ST',
        dateOfBirth: '2003-02-04',
        nationality: 'Denmark',
        club: 'Manchester United',
      },
      {
        name: 'Yussuf Poulsen',
        position: 'ST',
        dateOfBirth: '1994-06-15',
        nationality: 'Denmark',
        club: 'RB Leipzig',
      },
      {
        name: 'Kasper Dolberg',
        position: 'ST',
        dateOfBirth: '1997-10-06',
        nationality: 'Denmark',
        club: 'Anderlecht',
      },
      {
        name: 'Mathias Jensen',
        position: 'CM',
        dateOfBirth: '1996-01-01',
        nationality: 'Denmark',
        club: 'Brentford',
      },
      {
        name: 'Christian Nørgaard',
        position: 'CDM',
        dateOfBirth: '1994-03-10',
        nationality: 'Denmark',
        club: 'Brentford',
      },
      {
        name: 'Rasmus Kristensen',
        position: 'RB',
        dateOfBirth: '1996-07-11',
        nationality: 'Denmark',
        club: 'Eintracht Frankfurt',
      },
      {
        name: 'Anders Dreyer',
        position: 'RW',
        dateOfBirth: '1998-05-02',
        nationality: 'Denmark',
        club: 'Anderlecht',
      },
      {
        name: 'Morten Hjulmand',
        position: 'CDM',
        dateOfBirth: '2000-06-11',
        nationality: 'Denmark',
        club: 'Sporting CP',
      },
      {
        name: 'Patrick Dorgu',
        position: 'LB',
        dateOfBirth: '2004-10-26',
        nationality: 'Denmark',
        club: 'Lecce',
      },
      {
        name: 'Gustav Isaksen',
        position: 'RW',
        dateOfBirth: '2001-04-19',
        nationality: 'Denmark',
        club: 'Lazio',
      },
    ],
  },
  Serbia: {
    crest:
      'https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg',
    players: [
      {
        name: 'Predrag Rajković',
        position: 'GK',
        dateOfBirth: '1995-10-31',
        nationality: 'Serbia',
        club: 'Mallorca',
      },
      {
        name: 'Vanja Milinković-Savić',
        position: 'GK',
        dateOfBirth: '1997-02-20',
        nationality: 'Serbia',
        club: 'Torino',
      },
      {
        name: 'Đorđe Petrović',
        position: 'GK',
        dateOfBirth: '1999-10-08',
        nationality: 'Serbia',
        club: 'Chelsea',
      },
      {
        name: 'Strahinja Pavlović',
        position: 'CB',
        dateOfBirth: '2001-05-24',
        nationality: 'Serbia',
        club: 'AC Milan',
      },
      {
        name: 'Nikola Milenković',
        position: 'CB',
        dateOfBirth: '1997-10-12',
        nationality: 'Serbia',
        club: 'Nottingham Forest',
      },
      {
        name: 'Miloš Veljković',
        position: 'CB',
        dateOfBirth: '1995-09-26',
        nationality: 'Serbia',
        club: 'Werder Bremen',
      },
      {
        name: 'Filip Mladenović',
        position: 'LB',
        dateOfBirth: '1991-02-15',
        nationality: 'Serbia',
        club: 'Legia Warsaw',
      },
      {
        name: 'Aleksandar Mitrović',
        position: 'ST',
        dateOfBirth: '1994-09-16',
        nationality: 'Serbia',
        club: 'Al-Hilal',
      },
      {
        name: 'Dušan Vlahović',
        position: 'ST',
        dateOfBirth: '2000-01-28',
        nationality: 'Serbia',
        club: 'Juventus',
      },
      {
        name: 'Dušan Tadić',
        position: 'LW',
        dateOfBirth: '1988-11-20',
        nationality: 'Serbia',
        club: 'Fenerbahçe',
      },
      {
        name: 'Sergej Milinković-Savić',
        position: 'CM',
        dateOfBirth: '1995-02-27',
        nationality: 'Serbia',
        club: 'Al-Hilal',
      },
      {
        name: 'Nemanja Gudelj',
        position: 'CDM',
        dateOfBirth: '1991-11-16',
        nationality: 'Serbia',
        club: 'Sevilla',
      },
      {
        name: 'Saša Lukić',
        position: 'CM',
        dateOfBirth: '1996-08-13',
        nationality: 'Serbia',
        club: 'Fulham',
      },
      {
        name: 'Andrija Živković',
        position: 'RW',
        dateOfBirth: '1996-07-11',
        nationality: 'Serbia',
        club: 'PAOK',
      },
      {
        name: 'Filip Kostić',
        position: 'LW',
        dateOfBirth: '1992-11-01',
        nationality: 'Serbia',
        club: 'Juventus',
      },
      {
        name: 'Lazar Samardžić',
        position: 'CAM',
        dateOfBirth: '2002-02-24',
        nationality: 'Serbia',
        club: 'Atalanta',
      },
      {
        name: 'Ivan Ilić',
        position: 'CM',
        dateOfBirth: '2001-03-17',
        nationality: 'Serbia',
        club: 'Torino',
      },
      {
        name: 'Veljko Birmancević',
        position: 'RW',
        dateOfBirth: '1998-03-05',
        nationality: 'Serbia',
        club: 'Sparta Prague',
      },
      {
        name: 'Luka Jović',
        position: 'ST',
        dateOfBirth: '1997-12-23',
        nationality: 'Serbia',
        club: 'AC Milan',
      },
      {
        name: 'Nemanja Matić',
        position: 'CDM',
        dateOfBirth: '1988-08-01',
        nationality: 'Serbia',
        club: 'Lyon',
      },
      {
        name: 'Stefan Mitrović',
        position: 'CB',
        dateOfBirth: '1990-03-22',
        nationality: 'Serbia',
        club: 'Girona',
      },
      {
        name: 'Marko Grujić',
        position: 'CM',
        dateOfBirth: '1996-04-13',
        nationality: 'Serbia',
        club: 'Porto',
      },
    ],
  },
};
